baseUrl = "http://yusufsheiqh.github.io/"
languageCode = "en-gb"
title = "Yusuf Sheikh"
theme = "hyde"

[menus]
  [[menus.main]]
  name = "Github"
  url = "https://github.com/yusufsheiqh/"

  [[menus.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/yusufsheikh/"

[params]
  description = "Software Engineer."
  layoutReverse = true
