baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"

[Menus]
  [[Menus.main]]
  Name = "Github"
  URL = "https://github.com/yusufsheiqh/"

  [[Menus.main]]
  Name = "LinkedIn"
  URL = "https://www.linkedin.com/in/yusufsheikh/"
